# Generated by Django 2.2.4 on 2019-08-29 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_score_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='name',
            new_name='user',
        ),
    ]
