# Generated by Django 2.2 on 2019-11-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='response',
            field=models.CharField(default='BOT', max_length=36),
        ),
    ]
