# Generated by Django 2.2 on 2019-11-14 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_conversacion_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversacion',
            old_name='enviadoPor',
            new_name='enviadopor',
        ),
    ]
