# Generated by Django 2.2 on 2019-11-21 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20191114_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('problema', models.CharField(max_length=1000)),
                ('atendido', models.BooleanField(default=False)),
                ('modelopc', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=150)),
            ],
        ),
    ]
