# Generated by Django 2.2 on 2019-11-21 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
